name: Deploy
on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        env:
            EC2_HOST: 54.205.245.221
            EC2_USER: ubuntu

        steps:
        - name: Install SSH Client
          run: sudo apt-get install -y openssh-client

        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.MY_EC2_KEYS }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
    

        - name: Add EC2 Host to Known Hosts
          run: |
            ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts


        - name: Pull Docker Images
          run: |
            ssh $EC2_USER@$EC2_HOST << 'EOF'
                echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
                
                # Download docker-compose.yml from GitHub
                curl -O https://github.com/chikadevops/Microservices-Sample/blob/main/docker-compose.yml

                # Pull the latest Docker images
                docker pull chikadev/auth-api:latest
                docker pull chikadev/todos-api:latest
                docker pull chikadev/users-api:latest
                docker pull chikadev/log-message-processor:latest
                docker pull chikadev/frontend:latest
            
                # Run Containers
                docker-compose up -d --remove-orphans
                
            EOF