name: Build and Push
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build Docker Images
              run: |
                docker build -t chikadev/auth-api ./auth-api
                docker build -t chikadev/todos-api ./todos-api
                docker build -t chikadev/users-api ./users-api
                docker build -t chikadev/log-message-processor ./log-message-processor
                docker build -t chikadev/frontend ./frontend

            - name: Push Docker Images
              run: |
                docker push chikadev/auth-api
                docker push chikadev/todos-api
                docker push chikadev/users-api
                docker push chikadev/log-message-processor
                docker push chikadev/frontend